export type Language = "en" | "es";

// Union wszystkich kluczy słownika.
// TypeScript wymusi kompletność obu języków (en i es muszą zawierać DOKŁADNIE te klucze).
// Dodanie klucza w słowniku = dodanie go również tutaj.
export type TranslationKey =
  // Navigation
  | "nav.serve"
  | "nav.products"
  | "nav.why"
  | "nav.contact"
  | "nav.langToggle"
  // Hero
  | "hero.badge"
  | "hero.title1"
  | "hero.title2"
  | "hero.sub"
  | "hero.tagline"
  | "hero.ctaWhatsApp"
  | "hero.ctaQuote"
  | "hero.ctaCall"
  // Ice bar
  | "iceBar.text"
  // Who We Serve
  | "serve.title1"
  | "serve.title2"
  | "serve.sub"
  | "serve.shop.title"
  | "serve.shop.text"
  | "serve.gas.title"
  | "serve.gas.text"
  | "serve.party.title"
  | "serve.party.text"
  | "serve.bar.title"
  | "serve.bar.text"
  | "serve.event.title"
  | "serve.event.text"
  // Products
  | "product.title1"
  | "product.title2"
  | "product.sub"
  | "product.regular.title"
  | "product.regular.text"
  | "product.mixology.title"
  | "product.mixology.text"
  | "product.bulk.title"
  | "product.bulk.text"
  // Stats
  | "stats.onDemand"
  | "stats.service"
  | "stats.quality"
  | "stats.fleet"
  // Why
  | "why.title1"
  | "why.title2"
  | "why.sub"
  | "why.fast.title"
  | "why.fast.text"
  | "why.price.title"
  | "why.price.text"
  | "why.quality.title"
  | "why.quality.text"
  | "why.local.title"
  | "why.local.text"
  | "why.flex.title"
  | "why.flex.text"
  | "why.love.title"
  | "why.love.text"
  // Testimonials
  | "testi.title1"
  | "testi.title2"
  | "testi.1.text"
  | "testi.1.author"
  | "testi.1.role"
  | "testi.2.text"
  | "testi.2.author"
  | "testi.2.role"
  | "testi.3.text"
  | "testi.3.author"
  | "testi.3.role"
  // How it works
  | "how.title1"
  | "how.title2"
  | "how.sub"
  | "how.1.title"
  | "how.1.text"
  | "how.2.title"
  | "how.2.text"
  | "how.3.title"
  | "how.3.text"
  | "how.4.title"
  | "how.4.text"
  // Contact
  | "contact.title1"
  | "contact.title2"
  | "contact.sub"
  | "contact.phoneLabel"
  | "contact.phoneNote"
  | "contact.emailLabel"
  | "contact.emailNote"
  | "contact.webLabel"
  | "contact.webNote"
  | "contact.addressLabel"
  | "contact.addressValue"
  | "contact.addressNote"
  | "contact.ctaWhatsApp"
  | "contact.ctaCall"
  // Footer
  | "footer.sub"
  | "footer.copy";

export type Translations = Record<Language, Record<TranslationKey, string>>;
